services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  go-app:
    image: cosmtrek/air
    container_name: app
    working_dir: /app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=443
      - PG_PASSWORD=${PG_PASSWORD}
      - ENV=${ENV}
      - PG_USER=${PG_USER}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "443:443"
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local