package whatsapp

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"os"
	"strconv"
	"strings"
)

const graphAPIVersion = "v21.0"

// WhatsApp Cloud API limits.
const (
	maxQuickReplyButtons = 3
	maxListRows          = 10
	maxButtonTitleLen    = 20
	maxListRowTitleLen   = 24
	maxCallbackIDLen     = 256
	maxInteractiveBody   = 1024
	maxTextBody          = 4096
)

// ProxyClient intercepts Telegram Bot API requests addressed to WhatsApp users
// and reroutes them to the WhatsApp Cloud API. All other requests pass through
// untouched.
type ProxyClient struct {
	Transport           http.RoundTripper
	WhatsAppToken       string
	WhatsAppPhoneNumber string
	// IsWhatsAppUser resolves whether a chat id belongs to a WhatsApp user
	// (normally backed by the stored User.Messenger field). When nil, the
	// chat-id heuristic is used.
	IsWhatsAppUser func(chatID int64) bool
}

func NewProxyClient(isWhatsAppUser func(chatID int64) bool) *ProxyClient {
	return &ProxyClient{
		Transport:           http.DefaultTransport,
		WhatsAppToken:       os.Getenv("WHATSAPP_TOKEN"),
		WhatsAppPhoneNumber: os.Getenv("WHATSAPP_PHONE_ID"),
		IsWhatsAppUser:      isWhatsAppUser,
	}
}

func (p *ProxyClient) isWhatsAppChat(chatID int64) bool {
	if p.IsWhatsAppUser != nil {
		return p.IsWhatsAppUser(chatID)
	}
	return IsWhatsAppID(chatID)
}

func (p *ProxyClient) RoundTrip(req *http.Request) (*http.Response, error) {
	if !strings.Contains(req.URL.Host, "api.telegram.org") {
		return p.Transport.RoundTrip(req)
	}

	payload, restore := parseTelegramRequest(req)
	if restore != nil {
		defer restore()
	}
	if payload == nil {
		return p.Transport.RoundTrip(req)
	}

	// Answering fake callback queries generated by the WhatsApp webhook
	// would make Telegram return an error, so short-circuit them here.
	if strings.Contains(req.URL.Path, "/answerCallbackQuery") {
		if id, _ := payload["callback_query_id"].(string); strings.HasPrefix(id, waCallbackIDPrefix) {
			return fakeTelegramResponse(true), nil
		}
		return p.Transport.RoundTrip(req)
	}

	chatID := extractChatID(payload)
	if chatID == 0 || !p.isWhatsAppChat(chatID) {
		return p.Transport.RoundTrip(req)
	}

	switch {
	case strings.Contains(req.URL.Path, "/sendMessage"),
		strings.Contains(req.URL.Path, "/editMessageText"):
		return p.sendWhatsAppMessage(chatID, payload)
	case strings.Contains(req.URL.Path, "/deleteMessage"),
		strings.Contains(req.URL.Path, "/sendChatAction"):
		return fakeTelegramResponse(true), nil
	case strings.Contains(req.URL.Path, "/sendDocument"):
		// Document export is not supported for WhatsApp users yet.
		return fakeTelegramResponse(false), nil
	}

	return p.Transport.RoundTrip(req)
}

// parseTelegramRequest reads a go-telegram/bot request body (multipart/form-data
// or JSON) into a generic payload map. It restores req.Body so the request can
// still be forwarded to Telegram when it isn't a WhatsApp one.
func parseTelegramRequest(req *http.Request) (map[string]interface{}, func()) {
	if req.Body == nil {
		return nil, nil
	}

	bodyBytes, err := io.ReadAll(req.Body)
	if err != nil {
		return nil, nil
	}
	restore := func() {}
	req.Body = io.NopCloser(bytes.NewReader(bodyBytes))

	if len(bodyBytes) == 0 {
		return nil, restore
	}

	contentType := req.Header.Get("Content-Type")
	mediaType, params, err := mime.ParseMediaType(contentType)

	payload := map[string]interface{}{}

	if err == nil && strings.HasPrefix(mediaType, "multipart/") {
		reader := multipart.NewReader(bytes.NewReader(bodyBytes), params["boundary"])
		for {
			part, errPart := reader.NextPart()
			if errPart != nil {
				break
			}
			// Skip file uploads, only collect plain form fields.
			if part.FileName() != "" {
				continue
			}
			value, _ := io.ReadAll(part)
			payload[part.FormName()] = string(value)
		}
	} else {
		if json.Unmarshal(bodyBytes, &payload) != nil {
			return nil, restore
		}
	}

	if len(payload) == 0 {
		return nil, restore
	}

	return payload, restore
}

func extractChatID(payload map[string]interface{}) int64 {
	switch v := payload["chat_id"].(type) {
	case string:
		id, _ := strconv.ParseInt(v, 10, 64)
		return id
	case float64:
		return int64(v)
	}
	return 0
}

// IsWhatsAppID reports whether a chat id actually is a WhatsApp phone number.
func IsWhatsAppID(id int64) bool {
	// WhatsApp users are keyed by phone number (12+ digits), Telegram chat
	// ids are currently well below 10^10.
	return id > 10000000000
}

func fakeTelegramResponse(success bool) *http.Response {
	respBody := `{"ok": true, "result": {"message_id": 1}}`
	if !success {
		respBody = `{"ok": false, "error_code": 400, "description": "Not supported for WhatsApp"}`
	}
	return &http.Response{
		StatusCode: 200,
		Body:       io.NopCloser(strings.NewReader(respBody)),
		Header:     make(http.Header),
	}
}

func (p *ProxyClient) sendWhatsAppMessage(chatID int64, payload map[string]interface{}) (*http.Response, error) {
	if p.WhatsAppToken == "" || p.WhatsAppPhoneNumber == "" {
		return fakeTelegramResponse(false), fmt.Errorf("WhatsApp credentials missing")
	}

	text, _ := payload["text"].(string)
	if parseMode, _ := payload["parse_mode"].(string); strings.EqualFold(parseMode, "html") {
		text = htmlToWhatsApp(text)
	}

	to := strconv.FormatInt(chatID, 10)
	buttons := extractKeyboardButtons(payload["reply_markup"])

	var waBody map[string]interface{}
	if len(buttons) > 0 {
		waBody = buildWhatsAppInteractive(to, truncateRunes(text, maxInteractiveBody), buttons)
	} else {
		waBody = buildWhatsAppText(to, truncateRunes(text, maxTextBody))
	}

	waBytes, err := json.Marshal(waBody)
	if err != nil {
		return fakeTelegramResponse(false), err
	}

	url := fmt.Sprintf("https://graph.facebook.com/%s/%s/messages", graphAPIVersion, p.WhatsAppPhoneNumber)
	waReq, err := http.NewRequest("POST", url, bytes.NewBuffer(waBytes))
	if err != nil {
		return fakeTelegramResponse(false), err
	}
	waReq.Header.Set("Authorization", "Bearer "+p.WhatsAppToken)
	waReq.Header.Set("Content-Type", "application/json")

	waResp, err := p.Transport.RoundTrip(waReq)
	if err != nil {
		fmt.Println("WhatsApp API request failed:", err)
		return fakeTelegramResponse(false), nil
	}
	defer waResp.Body.Close()

	if waResp.StatusCode >= 300 {
		respBody, _ := io.ReadAll(waResp.Body)
		fmt.Printf("WhatsApp API error (%d): %s\n", waResp.StatusCode, string(respBody))
		return fakeTelegramResponse(false), nil
	}

	return fakeTelegramResponse(true), nil
}

type waButton struct {
	ID    string
	Title string
}

// extractKeyboardButtons flattens a Telegram reply_markup (inline or reply
// keyboard, either as a JSON string from a form field or as a decoded map)
// into a list of buttons. For reply keyboards the button text doubles as id,
// which the webhook side routes back as a plain text message.
func extractKeyboardButtons(replyMarkup interface{}) []waButton {
	var markup map[string]interface{}

	switch v := replyMarkup.(type) {
	case string:
		if json.Unmarshal([]byte(v), &markup) != nil {
			return nil
		}
	case map[string]interface{}:
		markup = v
	default:
		return nil
	}

	rows, _ := markup["inline_keyboard"].([]interface{})
	if rows == nil {
		rows, _ = markup["keyboard"].([]interface{})
	}

	var buttons []waButton
	for _, rowInt := range rows {
		row, ok := rowInt.([]interface{})
		if !ok {
			continue
		}
		for _, btnInt := range row {
			btn, ok := btnInt.(map[string]interface{})
			if !ok {
				continue
			}
			title, _ := btn["text"].(string)
			if title == "" {
				continue
			}
			id, _ := btn["callback_data"].(string)
			if id == "" {
				id = title
			}
			if len(id) > maxCallbackIDLen {
				id = id[:maxCallbackIDLen]
			}
			buttons = append(buttons, waButton{ID: id, Title: title})
		}
	}

	return buttons
}

func buildWhatsAppText(to string, text string) map[string]interface{} {
	return map[string]interface{}{
		"messaging_product": "whatsapp",
		"recipient_type":    "individual",
		"to":                to,
		"type":              "text",
		"text": map[string]interface{}{
			"preview_url": false,
			"body":        text,
		},
	}
}

func buildWhatsAppInteractive(to string, text string, buttons []waButton) map[string]interface{} {
	if text == "" {
		text = "👇"
	}

	if len(buttons) <= maxQuickReplyButtons {
		waButtons := make([]map[string]interface{}, 0, len(buttons))
		for _, b := range buttons {
			waButtons = append(waButtons, map[string]interface{}{
				"type": "reply",
				"reply": map[string]interface{}{
					"id":    b.ID,
					"title": truncateRunes(b.Title, maxButtonTitleLen),
				},
			})
		}

		return map[string]interface{}{
			"messaging_product": "whatsapp",
			"to":                to,
			"type":              "interactive",
			"interactive": map[string]interface{}{
				"type": "button",
				"body": map[string]interface{}{"text": text},
				"action": map[string]interface{}{
					"buttons": waButtons,
				},
			},
		}
	}

	if len(buttons) > maxListRows {
		buttons = buttons[:maxListRows]
	}

	listItems := make([]map[string]interface{}, 0, len(buttons))
	seen := map[string]bool{}
	for _, b := range buttons {
		title := truncateRunes(b.Title, maxListRowTitleLen)
		// WhatsApp rejects lists with duplicate row titles.
		if seen[title] {
			continue
		}
		seen[title] = true
		listItems = append(listItems, map[string]interface{}{
			"id":    b.ID,
			"title": title,
		})
	}

	return map[string]interface{}{
		"messaging_product": "whatsapp",
		"to":                to,
		"type":              "interactive",
		"interactive": map[string]interface{}{
			"type": "list",
			"body": map[string]interface{}{"text": text},
			"action": map[string]interface{}{
				"button": "Options",
				"sections": []map[string]interface{}{
					{
						"title": "Options",
						"rows":  listItems,
					},
				},
			},
		},
	}
}

func truncateRunes(s string, l int) string {
	runes := []rune(s)
	if len(runes) > l {
		return string(runes[:l])
	}
	return s
}
